### NumPy module

In [1]:
import numpy as np

In [2]:
# Create an 1d array from a list

lst = [0,1,2,3,4]
arr1d = np.array(lst)
type(arr1d)

numpy.ndarray

In [45]:
#lst + 2

In [4]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [5]:
lst2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(lst2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr2d.dtype

dtype('int64')

In [7]:
arr2d_f = np.array(lst2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [8]:
# Convert to 'str' datatype

arr2d_f.astype('str')

array([['0.0', '1.0', '2.0'],
       ['3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0']], dtype='<U32')

In [9]:
# Create an object array to hold numbers as well as strings

arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [10]:
arr1d_obj.tolist()

[1, 'a']

In [11]:
# shape
arr2d.shape

(3, 3)

In [12]:
#size
arr2d.size

9

In [13]:
# number of dimensions
arr2d.ndim

2

In [14]:
# Extract the first 2 rows and columns
arr2d[:2, :2]

array([[0, 1],
       [3, 4]])

In [15]:
# Get the boolean output by applying the condition to each element.
arr2d > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [16]:
arr2d[arr2d > 4]

array([5, 6, 7, 8])

In [17]:
# Insert a nan and an inf
array = np.array([[1, 2, 3], [4, 7, 8]], dtype=float)
array[1,1] = np.nan  # not a number
array[1,2] = np.inf  # infinite
array

array([[ 1.,  2.,  3.],
       [ 4., nan, inf]])

In [18]:
# Replace nan and inf with 0
missing = np.isnan(array) | np.isinf(array)
array[missing] = 0  
array

array([[1., 2., 3.],
       [4., 0., 0.]])

In [19]:
# mean, max and min
print(array.mean())
print(array.max())
print(array.min())

1.6666666666666667
4.0
0.0


In [20]:
np.amin(array, axis=0)

array([1., 0., 0.])

In [21]:
np.amin(array, axis=1)

array([1., 0.])

In [22]:
# Cumulative sum
np.cumsum(array)

array([ 1.,  3.,  6., 10., 10., 10.])

In [23]:
# Copy portion of array to array1
array1 = array[:2, :2].copy()
array1[:1, :1] = 10  
array1

array([[10.,  2.],
       [ 4.,  0.]])

In [24]:
array

array([[1., 2., 3.],
       [4., 0., 0.]])

In [25]:
# Reshaping
array.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [0., 0.]])

In [26]:
array.reshape(1, 6)

array([[1., 2., 3., 4., 0., 0.]])

In [27]:
array.flatten()

array([1., 2., 3., 4., 0., 0.])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5, -1, -2)

array([5, 3, 1])

In [30]:
# Start at 0 and end at 10
np.linspace(start=0, stop=10, num=21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# np.random module

# Pseudo-random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.56973433 0.54011297]
 [0.68988703 0.58610816]]


In [35]:
# One random number between [0,1)
np.random.random()

0.6274366051976441

In [36]:
np.random.random(size =[2,2])

array([[0.55676416, 0.57258484],
       [0.21051732, 0.6054569 ]])

In [37]:
# Random integers between [0, 10) of shape 2,2
np.random.randint(0, 10, size=[2,2])

array([[8, 2],
       [0, 8]])

In [38]:
np.random.rand(2,2)

array([[0.31336914, 0.88958012],
       [0.24529891, 0.95043305]])

In [39]:
np.random.seed(42)
np.random.rand(2,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [40]:
# Get the unique items and their counts
np.random.seed(42)
array = np.random.randint(0, 10, size=[5,2])
uniqs, counts = np.unique(array, return_counts=True)

In [41]:
array

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4]])

In [42]:
uniqs

array([2, 3, 4, 6, 7, 9])

In [43]:
counts

array([1, 1, 2, 3, 2, 1])

Further reading:   
https://habr.com/ru/post/352678/  
https://devpractice.ru/numpy-useful-functions/ (linear algebra)  
https://numpy.org/doc/1.17/reference/  